import React, { useState, useMemo, useEffect } from 'react';
import {
  SafeAreaView,
  View,
  Text,
  StyleSheet,
  FlatList,
  ScrollView,
  Pressable,
  StatusBar,
  Linking,
  ActivityIndicator,
  Image,
  TextInput,
} from 'react-native';

// Yeni oluşturduğumuz bileşeni içe aktarıyoruz
import ProductCard from './components/ProductCard';

const PHONE_NUMBER = '525529275019';
const LOGO_IMAGE = require('./assets/icon.png');

// --- VERİLER (DATA) ---
const TURKISH_WORDS = [
  { tr: 'Merhaba', es: 'Hola', note: 'Saludo general' },
  { tr: 'Günaydın', es: 'Buenos días', note: 'En la mañana' },
  { tr: 'İyi akşamlar', es: 'Buenas noches', note: 'Saludo en la noche' },
  { tr: 'Hoş geldiniz', es: 'Bienvenido(a)', note: 'Al recibir a alguien o en restaurante' },
  { tr: 'Güle güle', es: 'Adiós', note: 'Cuando alguien se va' },
  { tr: 'Nasılsın?', es: '¿Cómo estás?', note: 'Entre amigos, informal' },
  { tr: 'Nasılsınız?', es: '¿Cómo está?', note: 'Formal, con respeto' },
  { tr: 'İyiyim, teşekkürler', es: 'Estoy bien, gracias', note: 'Respuesta típica' },
  { tr: 'Teşekkürler', es: 'Gracias', note: 'Agradecimiento general' },
  { tr: 'Çok teşekkürler', es: 'Muchas gracias', note: 'Agradecimiento fuerte' },
  { tr: 'Lütfen', es: 'Por favor', note: 'Para pedir algo con cortesía' },
  { tr: 'Rica ederim', es: 'De nada / Con gusto', note: 'Respuesta a “gracias”' },
  { tr: 'Özür dilerim', es: 'Perdón / Disculpa', note: 'Cuando cometes un error' },
  { tr: 'Evet', es: 'Sí', note: 'Respuesta afirmativa' },
  { tr: 'Hayır', es: 'No', note: 'Respuesta negativa' },
  { tr: 'Anlamadım', es: 'No entendı́', note: 'Cuando no entiendes' },
  { tr: 'Yavaş konuşur musun?', es: '¿Puedes hablar despacio?', note: 'Turco muy rápido' },
  { tr: 'Türkçe bilmiyorum', es: 'No hablo turco', note: 'Para aclarar' },
  { tr: 'Biraz Türkçe biliyorum', es: 'Hablo un poco de turco', note: 'Nivel básico' },
  { tr: 'Burası neresi?', es: '¿Dónde estoy?', note: 'Cuando estás perdido' },
  { tr: '... nerededir?', es: '¿Dónde está...?', note: 'Para preguntar por un lugar' },
  { tr: 'Otobüs durağı nerede?', es: '¿Dónde está la parada de camión?', note: 'Transporte público' },
  { tr: 'Metro durağı nerede?', es: '¿Dónde está la estación de metro?', note: 'Transporte público' },
  { tr: 'Sol', es: 'Izquierda', note: 'Dirección' },
  { tr: 'Sağ', es: 'Derecha', note: 'Dirección' },
  { tr: 'Düz', es: 'Derecho / recto', note: 'Seguir derecho' },
  { tr: 'Menü alabilir miyim?', es: '¿Me puede traer el menú, por favor?', note: 'En restaurante' },
  { tr: 'Bir masa istiyorum', es: 'Quiero una mesa', note: 'Al llegar al restaurante' },
  { tr: 'İki kişilik masa', es: 'Mesa para dos personas', note: 'Reservar lugar' },
  { tr: 'Ne tavsiye edersiniz?', es: '¿Qué me recomienda?', note: 'Pedir recomendación' },
  { tr: 'Hesap lütfen', es: 'La cuenta, por favor', note: 'Para pagar' },
  { tr: 'Paket yapar mısınız?', es: '¿Me lo puede poner para llevar?', note: 'Para llevar' },
  { tr: 'Acısız olsun lütfen', es: 'Sin picante, por favor', note: 'Si no quieres picante' },
  { tr: 'Bir çay lütfen', es: 'Un té turco, por favor', note: 'Pedir çay' },
  { tr: 'Bu ne kadar?', es: '¿Cuánto cuesta esto?', note: 'Precio de un producto' },
  { tr: 'İndirim var mı?', es: '¿Hay descuento?', note: 'Preguntar por promoción' },
  { tr: 'Bir kilo ... istiyorum', es: 'Quiero un kilo de...', note: 'Frutas, verduras, etc.' },
  { tr: 'Poşet alabilir miyim?', es: '¿Me puede dar una bolsa?', note: 'En caja / súper' },
  { tr: 'Kredi kartı geçiyor mu?', es: '¿Aceptan tarjeta?', note: 'Forma de pago' },
  { tr: 'Taksi çağırabilir misiniz?', es: '¿Puede llamar un taxi, por favor?', note: 'En hotel o restaurante' },
  { tr: 'Havalimanına gitmek istiyorum', es: 'Quiero ir al aeropuerto', note: 'Taxi / transporte' },
  { tr: 'Ne kadar sürer?', es: '¿Cuánto tiempo tarda?', note: 'Duración del trayecto' },
  { tr: 'Yardım eder misiniz?', es: '¿Me puede ayudar?', note: 'Pedir ayuda' },
  { tr: 'Doktor lazım', es: 'Necesito un doctor', note: 'Emergencia médica' },
  { tr: 'Polisi arayın lütfen', es: 'Llame a la policía, por favor', note: 'Emergencia seria' },
];
